In [23]:
# pip install pycaret on your conda environment
# !pip install pycaret

In [35]:
# install libraries
import pandas as pd
from pycaret.regression import *

In [36]:
# set the maximum number of column to display:
pd.set_option('display.max_columns', 100)

#  datload our dataset ->> in this case "housing_price_prediction.csv"
housing = pd.read_csv("housing_price_prediction.csv")
housing.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [37]:
# Explore the dataset
housing.shape

(1460, 81)

In [53]:
housing.dtypes.value_counts()

object     43
int64      35
float64     3
dtype: int64

In [38]:
# lest check missing value 
missing_values = housing.isnull().sum()
missing_columns = missing_values[missing_values>0]

for col, count in missing_columns.items():
    print(f"Column {col}) has {count} missing values")

Column LotFrontage) has 259 missing values
Column Alley) has 1369 missing values
Column MasVnrType) has 8 missing values
Column MasVnrArea) has 8 missing values
Column BsmtQual) has 37 missing values
Column BsmtCond) has 37 missing values
Column BsmtExposure) has 38 missing values
Column BsmtFinType1) has 37 missing values
Column BsmtFinType2) has 38 missing values
Column Electrical) has 1 missing values
Column FireplaceQu) has 690 missing values
Column GarageType) has 81 missing values
Column GarageYrBlt) has 81 missing values
Column GarageFinish) has 81 missing values
Column GarageQual) has 81 missing values
Column GarageCond) has 81 missing values
Column PoolQC) has 1453 missing values
Column Fence) has 1179 missing values
Column MiscFeature) has 1406 missing values

In [40]:
# initialize the environment and prepare data for modeling
caret_df = setup(data = housing, target = "SalePrice", session_id= 123)

# session_id: you can put any random number it wont mean anything. In this case i put 123.

# if you want to explictily define the categorical variable while initialize module you can do it.
# But in this case pycared will automatically do it.
# categorical_features = ["MSZoning", "Street", "...", "..."]

# if you think you want to avoid some features to ignore in our model you can explictily declare it. 
# ignore_features=[‘total_production’]

In [41]:
# The two_words
# now time to compare different regression model with our dataset. 
best = compare_models()

Processing:   0%|          | 0/81 [00:00<?, ?it/s]

In [42]:
# Analyze the model
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [7]:
# plot the model in confusion matrix
predict_model(best)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,prediction_label
147,148,60,RL,NaN,9505,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2010,WD,Normal,222500,222602.144163
676,677,70,RM,60.0,9600,Pave,Grvl,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2006,WD,Normal,87000,90126.596293
1304,1305,160,RM,32.0,3363,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2006,WD,Normal,130000,155611.351984
1372,1373,60,RL,75.0,9750,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2006,WD,Normal,274300,245305.656189
1427,1428,50,RL,60.0,10930,Pave,Grvl,Reg,Bnk,AllPub,...,NaN,NaN,NaN,0,4,2008,WD,Normal,140000,136614.143785
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1096,1097,70,RM,60.0,6882,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,3,2007,WD,Normal,127000,112778.665133
637,638,190,RM,50.0,6000,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,11,2009,WD,Normal,93000,108637.475303
753,754,60,RL,80.0,10240,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,3,2006,WD,Normal,275500,275193.086796
554,555,60,RL,85.0,10625,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,8,2008,WD,Normal,284000,242153.959355
376,377,85,RL,57.0,8846,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,7,2006,WD,Normal,148000,135634.535420

In [11]:
tuned_freg = tune_model(best)

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [47]:
# No, for some reason i dont want to use best model, i want use this particular model: in this case random forest regression
rf = create_model("rf")
evaluate_model(rf)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

## Resourcs: If you want to dig deeper, i gather few resources
#### https://www.mdpi.com/2076-3417/13/8/5180
#### https://pycaret.gitbook.io/docs/get-started/quickstart#regression
#### https://en.wikipedia.org/wiki/Multilevel_model
#### https://www.analyticsvidhya.com/blog/2021/07/automl-using-pycaret-with-a-regression-use-case/
"""